apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zat7gg5pq-python
  janus-idp.io/tekton: zat7gg5pq-python
  backstage.io/kubernetes-id: zat7gg5pq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zat7gg5pq-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
