apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zat7gg5pq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zat7gg5pq-python 
  name: zat7gg5pq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zat7gg5pq-python 
